#!/bin/bash
# Enable debugging
set -e
# Add /usr/bin to PATH with gfortran-11
export PATH=/usr/bin:$PATH

# Create a symbolic link in a user-writable directory
mkdir -p $HOME/.local/bin
ln -sf /usr/bin/gfortran-11 $HOME/.local/bin/gfortran
export PATH=$HOME/.local/bin:$PATH

# Run the keep-alive script in the background
nohup python keep_alive.py > keep_alive.log 2>&1 &
